name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *" # Her 12 saatte bir otomatik çalışır
  workflow_dispatch: # Manuel olarak başlatmana izin verir
  push:
    branches:
    - master # Eğer ana branch adın 'main' ise burayı 'main' yap

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Dosyayı kaydedebilmesi için bu izin şart
    
    steps:
      - uses: actions/checkout@v3

      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: islam767
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push changes
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
